const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("poly", {
  status: () => ipcRenderer.invoke("status"),
  pickFolder: () => ipcRenderer.invoke("pick-folder"),
  saveKey: (k) => ipcRenderer.invoke("save-key", k),
  listFiles: (dir) => ipcRenderer.invoke("list-files", dir),
  readFile: (file) => ipcRenderer.invoke("read-file", file),
  readXlsx: (file) => ipcRenderer.invoke("read-xlsx", file),
  capture: (file) => ipcRenderer.invoke("capture", file),
  runAgent: (goal, cwd, attachments) => ipcRenderer.send("run-agent", { goal, cwd, attachments }),
  stopAgent: () => ipcRenderer.send("stop-agent"),
  pickAttachments: () => ipcRenderer.invoke("pick-attachments"),
  attachmentKind: (p) => ipcRenderer.invoke("attachment-kind", p),
  saveBlob: (name, dataUrl) => ipcRenderer.invoke("save-blob", { name, dataUrl }),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  exportPdf: (opts) => ipcRenderer.invoke("export-pdf", opts),
  // auth + consent + telemetry
  authStatus: () => ipcRenderer.invoke("auth-status"),
  signInGoogle: () => ipcRenderer.invoke("sign-in-google"),
  signOut: () => ipcRenderer.invoke("sign-out"),
  acceptTerms: (telemetry) => ipcRenderer.invoke("accept-terms", telemetry),
  setTelemetry: (on) => ipcRenderer.invoke("set-telemetry", on),
  reportError: (ev) => ipcRenderer.send("report-error", ev),
  onAuthChanged: (cb) => ipcRenderer.on("auth-changed", (_e, s) => cb(s)),
  // local model management
  localCatalog: () => ipcRenderer.invoke("local-catalog"),
  cloudCatalog: () => ipcRenderer.invoke("cloud-catalog"),
  setLocalUrl: (url) => ipcRenderer.invoke("set-local-url", url),
  localList: () => ipcRenderer.invoke("local-list"),
  localPull: (id) => ipcRenderer.send("local-pull", id),
  localRm: (id) => ipcRenderer.invoke("local-rm", id),
  onLocalPullDone: (cb) => ipcRenderer.on("local-pull-done", (_e, d) => cb(d)),
  answer: (text) => ipcRenderer.send("answer", text),
  setupLocal: () => ipcRenderer.send("setup-local"),
  onEvent: (cb) => ipcRenderer.on("agent-event", (_e, ev) => cb(ev)),
  onLog: (cb) => ipcRenderer.on("agent-log", (_e, s) => cb(s)),
  onAuto: (cb) => ipcRenderer.on("auto", (_e, a) => cb(a)),
  // supervision mode
  superviseRun: (opts) => ipcRenderer.send("supervise-run", opts),
  superviseContinue: (opts) => ipcRenderer.send("supervise-run", { ...opts, cont: true }),
  superviseStop: () => ipcRenderer.send("supervise-stop"),
  onSuperviseEvent: (cb) => ipcRenderer.on("supervise-event", (_e, ev) => cb(ev)),
});
